// view/Post/show.svelte
<script>
  import Link from './Link.svelte';
  let {post} = $props();
</script>

<h1>Show Post</h1>

<table border="1" cellpadding="10">
  <thead>
    {#each Object.keys(post) as key}
      <th>{key}</th>
    {/each}
  </thead>
  <tbody>
    <tr>
      {#each Object.keys(post) as key}
        <td>{post[key]}</td>
      {/each}
    </tr>
  </tbody>
</table>

<br />

<Link href={`/`}>Back</Link>
<span> | </span>
<Link href={`/${post.id || 0}/edit`}>Edit</Link>

<style>
  table {
    border-collapse: collapse;
  }
</style>

// vuedemo/view/src/index/show.vue
<script setup>
import Link from '../Link.vue';
const props = defineProps({
  post: Object
});
</script>

<template>
  <div>
    <h1>Show Post</h1>

    <table border="1" cellpadding="10">
      <thead>
        <tr>
          <th v-for="key in Object.keys(props.post)" :key="key">{{ key }}</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td v-for="key in Object.keys(props.post)" :key="key">{{ props.post[key] }}</td>
        </tr>
      </tbody>
    </table>

    <component :is="Link" href="/">Back</component>
    <span> | </span>
    <component :is="Link" :href="`/post/${props.post.id || 0}/edit`">Edit</component>
  </div>
</template>

<style>
table {
  border-collapse: collapse;
}
</style>
